
name: Build Workflow

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Print Versions
        run: |
          python --version
          pip --version
      - name: Install requirements
        run: |
          pip install pyinstaller
      - name: Run PyInstaller
        run: |
          pyinstaller main.spec
      - name: See dist directory
        run: ls dist
      - uses: actions/upload-artifact@master
        with:
          name: Windows
          path: dist/main.exe
  build-windows-x86:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x86'
      - name: Print Versions
        run: |
          python --version
          pip --version
      - name: Install requirements
        run: |
          pip install pyinstaller
      - name: Run PyInstaller
        run:  pyinstaller main.spec
      - name: See dist directory
        run: ls dist
      - uses: actions/upload-artifact@master
        with:
          name: Windows-x86
          path: dist/main.exe

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Print Versions
        run: |
          python --version
          pip --version
      - name: Install requirements
        run: |
          pip install pyinstaller
      - name: Run PyInstaller
        run: |
          pyinstaller SFCircuit.spec
      - name: See dist directory
        run: ls dist
      - uses: actions/upload-artifact@master
        with:
          name: Ubuntu
          path: dist

  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Print Versions
        run: |
          python --version
          pip --version
      - name: Install requirements
        run: |
          pip install pyinstaller
      - name: Run PyInstaller
        run:  pyinstaller SFCircuit.spec
      - name: See dist directory
        run: ls dist
      - uses: actions/upload-artifact@master
        with:
          name: MacOSApp
          path: dist
